### ISSUE TITLE
Unclear binary search tree task explanation

### ISSUE THREAD

**Issue by Deedone** [mrwhythat/academia#1]
Binary search tree is supposed to be sorted in a certain way. The task says that tree should have symbols as keys, but as per my understanding LISP symbols cannot be compared(only checked for equality). So by which criteria should we choose a branch for new key?

**Comment by mrwhythat** [comment]
Lisp has an interesting concept of *string designators* - objects that may be used as strings (naming things) but are not necessarily strings themselves. Precise [definition from the standard](http://www.lispworks.com/documentation/HyperSpec/Body/26_glo_s.htm#string_designator) says:

> **string designator** n. a designator for a string; that is, an
> object that denotes a string and that is one of: a character
> (denoting a singleton string that has the character as its only
> element), a symbol (denoting the string that is its name), or a
> string (denoting itself).

All Lisp's [string comparison functions](http://www.lispworks.com/documentation/HyperSpec/Body/f_stgeq_.htm) take string designators as arguments, so comparing the symbols using these functions effectively lexicographically compares their names, which is exactly what we need for this lab.

**Comment by Deedone** [comment]
Thank you for clearing this out

**Comment by mrwhythat** [comment]
No problem! That was a very good question. I was oblivious about this concept for the first few years and used to do the `(symbol-name <symbol>)` before comparison. I'll update the task description with a hint shortly.
